spring.application.name=spring-ai-demo
spring.ai.google.genai.api-key=AIzaSyDAiMKuhbld9KTkuCJFh3HGTziG1JXQquU
spring.ai.google.genai.api-version=v1
spring.ai.google.genai.chat.options.model=gemini-2.5-flash